// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseConnection():Promise<void>;

export function Connect(arg1:string,arg2:string,arg3:string):Promise<main.DBConnection>;

export function Table(arg1:string):Promise<main.TableData>;

export function Tables():Promise<Array<string>>;
