// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseConnection() {
  return window['go']['main']['App']['CloseConnection']();
}

export function Connect(arg1, arg2, arg3) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3);
}

export function Table(arg1) {
  return window['go']['main']['App']['Table'](arg1);
}

export function Tables() {
  return window['go']['main']['App']['Tables']();
}
